'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  {"name": "about", "href": "/about"},
  {"name": "devops", "href": "/devops"},
]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname()
  console.log(pathname);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {navLinks.map((link)=> {
          const isActive = 
            pathname === link.href ||
            (pathname.startsWith(link.href) && link.href != '/' )
          return (
            <Link className={isActive ? "font-bold mr-4 bg-red-600" : "bg-red-600 text-blue-500 mr-4" } href={link.href} key={link.name}>
              {link.name}
            </Link>
          )
        })}
        {children}
      </body>
    </html>
  );
}
